#!/bin/bash

set -e

# crosstool-ng
rm -rf build
mkdir -p build
sudo mkdir -p /opt
sudo chmod 0777 /opt
sudo rm -rf /opt/ct-ng
pushd builder
./bootstrap
./configure --prefix=/opt/ct-ng
make -j"$(nproc)"
sudo make install
popd
