#!/bin/bash
set -e

TARGET=$1
CONFIG_FILE="build/.config"

TARGET_ASFLAGS=""
TARGET_CFLAGS=""
TARGET_LDFLAGS=""

case "${TARGET}" in
    alpha-unknown-linux-uclibc)
        export ARCH="alpha"
        export TARGET_CFLAGS="-mcpu=ev67 -mieee -fno-use-linker-plugin"
        export TARGET_LDFLAGS="-Wl,--no-check-sections -fno-use-linker-plugin"
        ;;
    loongarch64-unknown-linux-uclibc)
        TARGET_CFLAGS="-march=loongarch64 -mabi=lp64d -mtune=la464"
        ;;
    powerpc-unknown-linux-uclibc | powerpcle-unknown-linux-uclibc)
        TARGET_CFLAGS="-msecure-plt"
        ;;
    powerpc64-unknown-linux-uclibc)
        TARGET_CFLAGS="-mpowerpc64 -m64 -mminimal-toc"
        ;;
    powerpc64le-unknown-linux-uclibc)
        TARGET_CFLAGS="-mpowerpc64 -m64 -mabi=elfv2 -mminimal-toc"
        ;;
    riscv32-unknown-linux-uclibc)
        TARGET_CFLAGS="-march=rv32g -mabi=ilp32d"
        ;;
    riscv64-unknown-linux-uclibc)
        TARGET_CFLAGS="-march=rv64gc -mabi=lp64d"
        ;;
    sparc-unknown-linux-uclibc)
        TARGET_CFLAGS="-mcpu=v9"
        ;;
    sparc64-unknown-linux-uclibc)
        TARGET_ASFLAGS="-m64"
        TARGET_CFLAGS="-mcpu=ultrasparc3 -Wno-pointer-to-int-cast"
        ;;
    s390-ibm-linux-uclibc)
        TARGET_CFLAGS="-march=z9-109 -m31"
        TARGET_LDFLAGS="-m31"
        ;;
    s390x-ibm-linux-uclibc)
        TARGET_CFLAGS="-march=z196 -m64"
        TARGET_LDFLAGS="-m64"
        ;;
    *)
        echo "Using default config settings for ${TARGET}"
        ;;
esac

# Inject flags into .config if they were set
if [[ -n "${TARGET_ASFLAGS}" ]]; then
    sed -i '/^CT_TARGET_ASFLAGS=/d' "$CONFIG_FILE"
    echo "CT_TARGET_ASFLAGS=\"${TARGET_ASFLAGS}\"" >> "$CONFIG_FILE"
fi
if [[ -n "${TARGET_CFLAGS}" ]]; then
    sed -i '/^CT_TARGET_CFLAGS=/d' "$CONFIG_FILE"
    echo "CT_TARGET_CFLAGS=\"${TARGET_CFLAGS}\"" >> "$CONFIG_FILE"
fi
if [[ -n "${TARGET_LDFLAGS}" ]]; then
    sed -i '/^CT_TARGET_LDFLAGS=/d' "$CONFIG_FILE"
    echo "CT_TARGET_LDFLAGS=\"${TARGET_LDFLAGS}\"" >> "$CONFIG_FILE"
fi
