#!/bin/bash
set -e

CONFIG_FILE="build/.config"

printf "CT_ALLOW_BUILD_AS_ROOT=y" >> "$CONFIG_FILE"
printf "CT_ALLOW_BUILD_AS_ROOT_SURE=y" >> "$CONFIG_FILE"
printf "CT_LOG_ALL=y" >> "$CONFIG_FILE"
printf 'CT_LOG_LEVEL_MAX="ALL"' >> "$CONFIG_FILE"
