#!/bin/bash

set -e

# crosstool-ng
sudo mkdir -p /opt
sudo chmod 0777 /opt
export CT_BIN="/opt/ct-ng/bin/ct-ng"
          if [ ! -f "$CT_BIN" ]; then
    pushd builder
    ./bootstrap
    ./configure --prefix=/opt/ct-ng
    make -j"$(nproc)"
    sudo make install
    popd
else
    echo -e "\x1b[92mcrosstool-ng already installed at $CT_BIN$\x1b[0m"
fi
