name: SSSH
'on':
  workflow_dispatch:
    inputs:
      target_build:
        description: Target?
        type: choice
        required: true
        options: [ aarch64-unknown-linux-uclibc, aarch64_be-unknown-linux-uclibc, alphaev67-unknown-linux-uclibc, arm-unknown-linux-uclibcgnueabi, arm-unknown-linux-uclibcgnueabihf, armv4t-unknown-linux-uclibcgnueabi, armv5-unknown-linux-uclibcgnueabi, armv6-unknown-linux-uclibcgnueabi, armv6-unknown-linux-uclibcgnueabihf, armv7-unknown-linux-uclibcgnueabi, armv7-unknown-linux-uclibcgnueabihf, hppa-unknown-linux-uclibc, i486-unknown-linux-uclibc, i586-unknown-linux-uclibc, i686-unknown-linux-uclibc, m68k-unknown-linux-uclibc, microblaze-xilinx-linux-uclibc, microblazeel-xilinx-linux-uclibc, mips-unknown-linux-uclibc, mips-unknown-linux-uclibcsf, mips64-unknown-linux-uclibc, mips64el-unknown-linux-uclibc, mipsel-unknown-linux-uclibc, mipsel-unknown-linux-uclibcsf, or1k-unknown-linux-uclibc, powerpc-unknown-linux-uclibc, powerpc-unknown-linux-uclibcsf, powerpc64-unknown-linux-uclibc, powerpc64le-unknown-linux-uclibc, powerpcle-unknown-linux-uclibc, powerpcle-unknown-linux-uclibcsf, riscv32-unknown-linux-uclibc, riscv64-unknown-linux-uclibc, s390-ibm-linux-uclibc, s390x-ibm-linux-uclibc, sh4-multilib-linux-uclibc, sparc-unknown-linux-uclibc, sparc64-unknown-linux-uclibc, x86_64-unknown-linux-uclibc ]
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - '${{ inputs.target_build }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true
      - name: Enable Kitware Repository
        run: |
          test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
      - name: CCACHE Shit
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y install apt-utils ccache ca-certificates gpg wget libzstd-dev

          cat >> $GITHUB_ENV << 'EOF'
          CCACHE_SLOPPINESS=file_macro,locale,time_macros
          CCACHE_NOHASHDIR=true
          CCACHE_COMPRESS=1
          CCACHE_COMPRESSLEVEL=6
          CCACHE_NOFILECLONE=true
          CCACHE_NOHARDLINK=true
          CCACHE_INODECACHE=true
          CCACHE_NLEVELS=4
          CCACHE_COMPILERCHECK=content
          CCACHE_DEPEND=true
          EOF

          # Setup CCACHE Dir
          sudo mkdir -p /mnt/ccache
          sudo chown -R $USER:$USER /mnt/ccache
          echo "CCACHE_DIR=/mnt/ccache" >> $GITHUB_ENV
          echo "CCACHE Dir Set!"
          # Setup tarballs dir for download caching
          #sudo mkdir -p /mnt/tarballs
          #sudo chown -R $USER:$USER /mnt/tarballs
          df -h
          echo "CCACHE Environment set!"
      - name: Enable the CCACHE
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: 'true'
          key: 'ccache-${{ runner.os }}-${{ matrix.target }}'
          restore-keys: |
            ccache-${{ runner.os }}-
          max-size: 5000MB
          verbose: 2
          save: true
      - name: SSH Server-ing
        uses: valeriangalliat/action-sshd-cloudflared@v4
